---
- name: Install dependencies
  apt:
    update_cache: false
    pkg:
      - bzip2

- name: Check if restic is installed
  stat:
    path: "/usr/bin/restic"
  register: stat_result_restic

- debug:
    msg: "Restic already installed"
  when: stat_result_restic.stat.exists

- name: Install restic
  block:

  - name: "Downloading restic from {{ restic_url }}"
    get_url:
      url: "{{ restic_url }}"
      dest: /tmp/restic.bz2

  - name: Unzip restic
    shell: bzip2 -dc /tmp/restic.bz2 > /usr/bin/restic

  - name: Make restic executable
    file: dest=/usr/bin/restic mode=a+x

  when: not stat_result_restic.stat.exists

- name: Check if autorestic is installed
  stat:
    path: "/usr/bin/autorestic"
  register: stat_result_autorestic

- debug:
    msg: "restic already installed"
  when: stat_result_autorestic.stat.exists

- name: Install autorestic
  block:

  - name: "Download restic from {{ autorestic_url }}"
    get_url:
      url: "{{ autorestic_url }}"
      dest: /tmp/autorestic.bz2

  - name: Unzip autorestic
    shell: bzip2 -dc /tmp/autorestic.bz2 > /usr/bin/autorestic

  - name: Make autorestic executable
    file: dest=/usr/bin/autorestic mode=a+x
  
  when: not stat_result_autorestic.stat.exists

- name: Ensure local backup path exists
  file:
    path: "{{ local_backup_path }}"
    state: directory
    mode: 0755
    owner: "{{ user_PUID }}"
    group: "{{ user_PGID }}"

- name: Install autorestic.yml configuration
  template:
    src: autorestic.yml.j2
    dest: "{{ autorestic_config_path }}"
    mode: 0600

- name: Initialize restic backends
  shell: autorestic -c "{{ autorestic_config_path }}" check

- name: Install autorestic cronjob
  cron:
    name: "autorestic backup"
    minute: "{{ autorestic_cronjob_minute }}"
    hour: "{{ autorestic_cronjob_hour }}"
    day: "{{ autorestic_cronjob_day }}"
    month: "{{ autorestic_cronjob_month }}"
    weekday: "{{ autorestic_cronjob_weekday }}"
    job: "/usr/bin/autorestic -c {{ autorestic_config_path }} backup -a --verbose && /usr/bin/autorestic -c {{ autorestic_config_path }} forget -a --verbose >> {{ autorestic_cronjob_logfile }} 2>&1"